# -*- coding: utf-8 -*-
"""ORAIL 프로젝트 산업경영공학과 12210588 고우현 cdad_anomaly_advanced.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtKSF-857kcQ-gxk2QBd7QNJdWJq7hIU
"""

import os
import random
import math
import argparse
import numpy as np
import pandas as pd
from PIL import Image, ImageOps
from tqdm import tqdm
from scipy.ndimage import gaussian_filter, binary_dilation

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms

from diffusers import UNet2DConditionModel, AutoencoderKL, DDPMScheduler, DDIMScheduler
from transformers import CLIPTextModel, CLIPTokenizer
import clip

def get_defect_specific_prompt(defect_name):
    d = defect_name.lower()
    if 'missing' in d:
        return "an empty spot on PCB where a component is missing, clean circuit board surface"
    elif 'melt' in d:
        return "melted and deformed plastic texture, heat damage, bubbly distorted shape"
    elif 'burnt' in d:
        return "black burnt marks, charred surface, dark smoke damage, carbonized texture"
    elif 'scratch' in d:
        return "a sharp thin scratch line on metal surface, metallic scuff, surface abrasion"
    elif 'dirt' in d:
        return "scattered dirt spots on PCB, grease stains, brown contamination"
    elif 'extra' in d or 'wrong' in d:
        return "a component placed in wrong position, misplaced part, unexpected object"
    else:
        return f"a clear {defect_name} defect on component, industrial damage, deformed shape"

def load_mask(mask_path):
    """마스크 로드 + 모든 범위 스케일링"""
    mask_np = np.array(Image.open(mask_path).convert("L"))
    if mask_np.max() < 10:
        if mask_np.max() > 0:
            mask_np = (mask_np.astype(float) / mask_np.max() * 255).astype(np.uint8)
    return Image.fromarray(mask_np)

def dilate_mask(mask_pil, pixels=15):
    mask_np = np.array(mask_pil.convert("L"))
    dilated = binary_dilation(mask_np > 10, iterations=pixels)
    return Image.fromarray((dilated * 255).astype(np.uint8))

def calculate_metrics(base_img, gen_img, mask_pil):
    base_np = np.array(base_img.resize((512, 512))).astype(float)
    gen_np  = np.array(gen_img.resize((512, 512))).astype(float)
    mask_np = np.array(mask_pil.resize((512, 512)).convert("L")).astype(float) / 255.0
    mask_np = np.expand_dims(mask_np, axis=-1)
    intensity = (np.abs(base_np - gen_np) * mask_np).sum() / (mask_np.sum() + 1e-6)
    bg_mask = 1.0 - mask_np
    mse  = ((base_np - gen_np) ** 2 * bg_mask).sum() / (bg_mask.sum() * 3 + 1e-6)
    psnr = 20 * math.log10(255.0 / math.sqrt(mse)) if mse > 1e-10 else 100.0
    return float(intensity), float(psnr)

def get_bbox_from_mask(mask_pil, class_id=0):
    mask_np = np.array(mask_pil.convert("L"))
    if mask_np.max() < 10:
        return None
    binary  = np.where(mask_np > 5, 255, 0).astype(np.uint8)
    rows = np.any(binary > 0, axis=1)
    cols = np.any(binary > 0, axis=0)
    if not np.any(rows) or not np.any(cols):
        return None
    ymin, ymax = np.where(rows)[0][[0, -1]]
    xmin, xmax = np.where(cols)[0][[0, -1]]
    h, w = binary.shape
    return [class_id,
            (xmin + xmax) / 2.0 / w,
            (ymin + ymax) / 2.0 / h,
            (xmax - xmin) / w,
            (ymax - ymin) / h]

def get_best_alignment(normal_img, defect_img, mask_img):
    """8가지 방향 비교 후 정상 이미지와 가장 유사한 방향 선택"""
    normal_np = np.array(normal_img.resize((256, 256))).astype(float)
    best_score, best_defect, best_mask = float('inf'), defect_img, mask_img
    for flip in [False, True]:
        for rot in [0, 90, 180, 270]:
            d = defect_img.copy()
            m = mask_img.copy()
            if flip:
                d = ImageOps.mirror(d)
                m = ImageOps.mirror(m)
            if rot > 0:
                d = d.rotate(rot, expand=True)
                m = m.rotate(rot, expand=True)
            d_np = np.array(d.resize((256, 256))).astype(float)
            m_np = np.array(m.resize((256, 256)).convert("L")).astype(float) / 255.0
            bg   = 1.0 - np.expand_dims(m_np, axis=-1)
            diff = ((normal_np - d_np) ** 2 * bg).mean()
            if diff < best_score:
                best_score, best_defect, best_mask = diff, d, m
    return best_defect, best_mask

class AnomalyMaskNetwork(nn.Module):
    """
    정상 이미지 + 결함 이미지 + 마스크 입력
    → 더 정밀한 결함 마스크 출력
    """
    def __init__(self):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Conv2d(7, 64,  3, padding=1), nn.BatchNorm2d(64),  nn.ReLU(),
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(128, 256, 3, padding=1), nn.BatchNorm2d(256), nn.ReLU(),
            nn.MaxPool2d(2),
        )
        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(256, 128, 2, stride=2), nn.BatchNorm2d(128), nn.ReLU(),
            nn.ConvTranspose2d(128, 64,  2, stride=2), nn.BatchNorm2d(64),  nn.ReLU(),
            nn.Conv2d(64, 1, 1),
            nn.Sigmoid()
        )

    def forward(self, normal, defect, mask):
        x = torch.cat([normal, defect, mask], dim=1)  # (B, 7, H, W)
        return self.decoder(self.encoder(x))

class AnomalyConditioner(nn.Module):
    def __init__(self):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Conv2d(4, 64,  3, padding=1),            nn.GroupNorm(8,  64),  nn.SiLU(),
            nn.Conv2d(64, 128, 4, stride=2, padding=1), nn.GroupNorm(16, 128), nn.SiLU(),
            nn.Conv2d(128, 4,  3, padding=1)
        )
        self.clip_model, _ = clip.load("ViT-L/14", device='cpu')
        for p in self.clip_model.parameters():
            p.requires_grad = False
        self.text_proj = nn.Linear(768, 768)

    def forward(self, normal, mask, texts, device):
        v_feat = self.encoder(torch.cat([normal, mask], dim=1))
        tok    = clip.tokenize(texts, truncate=True).to(device)
        with torch.no_grad():
            t_raw = self.clip_model.to(device).encode_text(tok).float()
        return v_feat, self.text_proj(t_raw).unsqueeze(1)

class DefectDataset(Dataset):
    def __init__(self, data_root, cat, defects, samples=50):
        self.data_root = data_root
        self.list      = []
        df      = pd.read_csv(os.path.join(data_root, cat, "image_anno.csv"))
        normals = df[df['label'].str.lower() == 'normal']['image'].tolist()

        for d in defects:
            rows = df[df['label'].str.contains(d, na=False)]
            if rows.empty or not normals:
                continue
            for _ in range(samples):
                r = rows.sample(1).iloc[0]
                self.list.append({
                    'cat':    cat,
                    'normal': random.choice(normals),
                    'defect': r['image'],
                    'mask':   r['mask'],
                    'd':      d
                })

    def __len__(self):
        return len(self.list)

    def __getitem__(self, i):
        s     = self.list[i]
        n_img = Image.open(os.path.join(self.data_root, s['normal'])).convert("RGB")
        d_img = Image.open(os.path.join(self.data_root, s['defect'])).convert("RGB")
        m_img = load_mask(os.path.join(self.data_root, s['mask']))


        d_al, m_al = get_best_alignment(n_img, d_img, m_img)

        n_t = transforms.ToTensor()(n_img.resize((512, 512))) * 2 - 1
        d_t = transforms.ToTensor()(d_al.resize((512, 512))) * 2 - 1
        m_t = transforms.ToTensor()(m_al.resize((512, 512)))

        return {
            "normal": n_t,
            "defect": d_t,
            "mask":   m_t,
            "text":   f"PCB {s['cat']} with {s['d']} defect"
        }


class CDADEngine:
    def __init__(self, device):
        self.device = device
        mid = "runwayml/stable-diffusion-v1-5"

        self.vae          = AutoencoderKL.from_pretrained(mid, subfolder="vae",          torch_dtype=torch.float16).to(device)
        self.tokenizer    = CLIPTokenizer.from_pretrained(mid,  subfolder="tokenizer")
        self.text_encoder = CLIPTextModel.from_pretrained(mid,  subfolder="text_encoder", torch_dtype=torch.float16).to(device)
        self.unet         = UNet2DConditionModel.from_pretrained(mid, subfolder="unet").to(device)
        self.noise_scheduler = DDPMScheduler.from_pretrained(mid, subfolder="scheduler")

        self.amn         = AnomalyMaskNetwork().to(device)
        self.defect_cond = AnomalyConditioner().to(device)
        self.gp_basis    = {}
        self.clip_eval, self.clip_prep = clip.load("ViT-L/14", device=device)

    def _encode_text(self, text):
        ids = self.tokenizer(
            text, padding="max_length", max_length=77,
            truncation=True, return_tensors="pt"
        ).input_ids.to(self.device)
        return self.text_encoder(ids)[0].float()


    def train_amn_step(self, batch, opt_amn):
        """
        정상 + 결함 + 마스크 → 정제된 마스크 학습
        """
        normal = batch['normal'].to(self.device)
        defect = batch['defect'].to(self.device)
        mask   = batch['mask'].to(self.device)

        n_256 = F.interpolate(normal, size=(256, 256))
        d_256 = F.interpolate(defect, size=(256, 256))
        m_256 = F.interpolate(mask,   size=(256, 256))

        pred = F.interpolate(self.amn(n_256, d_256, m_256), size=(512, 512))
        loss = F.binary_cross_entropy(pred, mask)
        loss.backward()
        opt_amn.step()
        opt_amn.zero_grad()
        return loss.item()


    def train_diffusion_step(self, batch, opt, task_id):
        """
        핵심:
        조건 = 정상 이미지 + 마스크
        target = 결함 이미지 latent
        → 정상의 마스크 영역에 결함을 생성하도록 학습
        """
        normal = batch['normal'].to(self.device)
        defect = batch['defect'].to(self.device)
        mask   = batch['mask'].to(self.device)
        txt    = batch['text']

        with torch.no_grad():
            defect_latent = self.vae.encode(defect.half()).latent_dist.sample().float() * 0.18215
            t_feat        = self._encode_text(txt[0])


        v_feat, _ = self.defect_cond(normal, mask, txt, self.device)
        v_resized = F.interpolate(v_feat, size=(64, 64), mode='bilinear', align_corners=False)

        noise = torch.randn_like(defect_latent)
        t     = torch.randint(0, 1000, (defect_latent.shape[0],), device=self.device).long()
        noisy = self.noise_scheduler.add_noise(defect_latent, noise, t)

        noise_pred = self.unet(
            noisy + v_resized * 0.5, t,
            encoder_hidden_states=t_feat
        ).sample


        m_small = F.interpolate(mask, size=(64, 64), mode='bilinear', align_corners=False)
        loss    = (F.mse_loss(noise_pred, noise, reduction='none') * (1 + m_small * 20)).mean()
        loss.backward()


        if task_id > 0:
            for p in self.unet.parameters():
                if p.grad is not None:
                    g = p.grad.view(-1)
                    for b in self.gp_basis.values():
                        b = b.to(self.device)
                        D = min(g.shape[0], b.shape[1])
                        g[:D] -= 0.8 * (g[:D] @ b[:, :D].T @ b[:, :D])

        opt.step()
        opt.zero_grad()
        return loss.item()


    def update_gp_basis(self, dl, task_id):
        self.unet.eval()
        grads = []
        with torch.no_grad():
            for i, b in enumerate(dl):
                if i >= 5:
                    break
                vf, _ = self.defect_cond(
                    b['normal'].to(self.device),
                    b['mask'].to(self.device),
                    b['text'], self.device
                )
                grads.append(vf.view(vf.shape[0], -1).cpu().numpy())
        if grads:
            _, _, Vt = np.linalg.svd(np.concatenate(grads, axis=0), full_matrices=False)
            self.gp_basis[task_id] = torch.tensor(Vt[:3], dtype=torch.float32)
        self.unet.train()


    @torch.no_grad()
    def generate_single(self, normal_img, defect_img, mask_img,
                        defect_name, cat, scale=15.0):
        """
        정상 이미지 입력
        → 마스크 위치에 결함 생성
        → 배경은 정상 이미지 그대로 유지
        """

        d_al, m_al = get_best_alignment(normal_img, defect_img, mask_img)

        n_512 = normal_img.resize((512, 512))
        d_512 = d_al.resize((512, 512))
        m_512 = m_al.resize((512, 512)).convert("L")
        n_np  = np.array(n_512).astype(float)


        n_t   = (transforms.ToTensor()(n_512).unsqueeze(0).to(self.device) * 2 - 1)
        d_t   = (transforms.ToTensor()(d_512).unsqueeze(0).to(self.device) * 2 - 1)
        m_t   = transforms.ToTensor()(m_512).unsqueeze(0).to(self.device)
        n_256 = F.interpolate(n_t, size=(256, 256))
        d_256 = F.interpolate(d_t, size=(256, 256))
        m_256 = F.interpolate(m_t, size=(256, 256))
        ref   = F.interpolate(self.amn(n_256, d_256, m_256), size=(512, 512))
        ref_np = (ref[0, 0].cpu().numpy() * 255).astype(np.uint8)


        m_np      = np.array(m_512)
        final_m   = np.where((m_np > 10) | (ref_np > 127), 255, 0).astype(np.uint8)
        if final_m.sum() < (m_np > 10).sum() * 0.3:
            final_m = m_np
        final_mask_pil = Image.fromarray(final_m)
        m_lat = transforms.ToTensor()(final_mask_pil).unsqueeze(0).to(self.device)
        m_lat = F.interpolate(m_lat, size=(64, 64), mode='bilinear', align_corners=False)


        pos_txt = f"PCB {cat} with {get_defect_specific_prompt(defect_name)}, realistic"
        neg_txt = "normal, clean, perfect, no defects, blurry, low quality"

        v_feat, _ = self.defect_cond(n_t, m_t, [pos_txt], self.device)
        v_feat_64 = F.interpolate(v_feat, size=(64, 64), mode='bilinear', align_corners=False)
        pos_feat  = self._encode_text(pos_txt)
        neg_feat  = self._encode_text(neg_txt)


        orig_latent = self.vae.encode(n_t.half()).latent_dist.sample().float() * 0.18215

        sch = DDIMScheduler.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="scheduler")
        sch.set_timesteps(50)


        full_noise = torch.randn_like(orig_latent)
        curr = orig_latent * (1 - m_lat) + full_noise * m_lat

        for t in sch.timesteps:
            t_tensor = torch.tensor([t], device=self.device).long()

            bg_noisy = sch.add_noise(orig_latent, torch.randn_like(orig_latent), t_tensor)
            curr     = curr * m_lat + bg_noisy * (1 - m_lat)


            inp        = torch.cat([curr + v_feat_64 * 1.0] * 2)
            noise_pred = self.unet(
                inp, t,
                encoder_hidden_states=torch.cat([neg_feat, pos_feat])
            ).sample
            n_neg, n_pos = noise_pred.chunk(2)
            guided       = n_neg + scale * (n_pos - n_neg)
            curr         = sch.step(guided, t, curr).prev_sample

        gen_raw = self.vae.decode(curr.half() / 0.18215).sample
        gen_np  = ((gen_raw[0].float().clamp(-1, 1) + 1) / 2 * 255).byte().permute(1, 2, 0).cpu().numpy()


        smooth_m = gaussian_filter(final_m.astype(float) / 255.0, sigma=0.8)[..., None]
        final    = (gen_np.astype(float) * smooth_m + n_np * (1 - smooth_m)).astype(np.uint8)
        final_img = Image.fromarray(final)

        toks      = clip.tokenize([f"PCB with {defect_name}", "clean PCB"]).to(self.device)
        clip_in   = self.clip_prep(final_img).unsqueeze(0).to(self.device)
        logits, _ = self.clip_eval(clip_in, toks)
        clip_score = logits.softmax(dim=-1)[0, 0].item()

        return final_img, final_mask_pil, clip_score


    @torch.no_grad()
    def generate_compound(self, normal_img, defect_imgs, mask_imgs,
                           defect_names, cat, scale=15.0):
        n_512  = normal_img.resize((512, 512))
        n_np   = np.array(n_512).astype(float)
        n_t    = (transforms.ToTensor()(n_512).unsqueeze(0).to(self.device) * 2 - 1)

        comb_m    = np.zeros((512, 512), dtype=np.float32)
        ref_masks = []

        for d_img, m_img in zip(defect_imgs, mask_imgs):
            d_al, m_al = get_best_alignment(normal_img, d_img, m_img)
            d_512 = d_al.resize((512, 512))
            m_512 = m_al.resize((512, 512)).convert("L")

            d_t   = (transforms.ToTensor()(d_512).unsqueeze(0).to(self.device) * 2 - 1)
            m_t   = transforms.ToTensor()(m_512).unsqueeze(0).to(self.device)
            ref   = F.interpolate(
                self.amn(
                    F.interpolate(n_t, size=(256, 256)),
                    F.interpolate(d_t, size=(256, 256)),
                    F.interpolate(m_t, size=(256, 256))
                ), size=(512, 512)
            )
            ref_np = (ref[0, 0].cpu().numpy() * 255).astype(np.uint8)
            m_np   = np.array(m_512)
            final_m = np.where((m_np > 10) | (ref_np > 127), 255, 0).astype(np.uint8)
            if final_m.sum() < (m_np > 10).sum() * 0.3:
                final_m = m_np

            ref_masks.append(Image.fromarray(final_m))
            comb_m = np.clip(comb_m + final_m / 255.0, 0, 1)

        comb_mask_pil = Image.fromarray((comb_m * 255).astype(np.uint8))
        m_lat = transforms.ToTensor()(comb_mask_pil).unsqueeze(0).to(self.device)
        m_lat = F.interpolate(m_lat, size=(64, 64), mode='bilinear', align_corners=False)

        pos_txt = (f"PCB {cat} with "
                   f"{' and '.join([get_defect_specific_prompt(d) for d in defect_names])}, realistic")
        neg_txt = "normal, clean, perfect, no defects, blurry, low quality"

        v_feat, _ = self.defect_cond(n_t, m_lat, [pos_txt], self.device)
        v_feat_64 = F.interpolate(v_feat, size=(64, 64), mode='bilinear', align_corners=False)
        pos_feat  = self._encode_text(pos_txt)
        neg_feat  = self._encode_text(neg_txt)

        orig_latent = self.vae.encode(n_t.half()).latent_dist.sample().float() * 0.18215

        sch = DDIMScheduler.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="scheduler")
        sch.set_timesteps(50)

        full_noise = torch.randn_like(orig_latent)
        curr = orig_latent * (1 - m_lat) + full_noise * m_lat

        for t in sch.timesteps:
            t_tensor = torch.tensor([t], device=self.device).long()
            bg_noisy = sch.add_noise(orig_latent, torch.randn_like(orig_latent), t_tensor)
            curr     = curr * m_lat + bg_noisy * (1 - m_lat)

            inp        = torch.cat([curr + v_feat_64 * 1.0] * 2)
            noise_pred = self.unet(
                inp, t,
                encoder_hidden_states=torch.cat([neg_feat, pos_feat])
            ).sample
            n_neg, n_pos = noise_pred.chunk(2)
            guided       = n_neg + scale * (n_pos - n_neg)
            curr         = sch.step(guided, t, curr).prev_sample

        gen_raw = self.vae.decode(curr.half() / 0.18215).sample
        gen_np  = ((gen_raw[0].float().clamp(-1, 1) + 1) / 2 * 255).byte().permute(1, 2, 0).cpu().numpy()

        smooth_m  = gaussian_filter(comb_m, sigma=0.8)[..., None]
        final     = (gen_np.astype(float) * smooth_m + n_np * (1 - smooth_m)).astype(np.uint8)
        final_img = Image.fromarray(final)

        toks      = clip.tokenize(["PCB with defects", "clean PCB"]).to(self.device)
        clip_in   = self.clip_prep(final_img).unsqueeze(0).to(self.device)
        logits, _ = self.clip_eval(clip_in, toks)
        clip_score = logits.softmax(dim=-1)[0, 0].item()

        return final_img, comb_mask_pil, ref_masks, clip_score

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--data_root",    type=str, required=True)
    parser.add_argument("--output_dir",   type=str, default="./results_final")
    parser.add_argument("--epochs",       type=int, default=70)
    parser.add_argument("--num_single",   type=int, default=100)
    parser.add_argument("--num_compound", type=int, default=200)
    args = parser.parse_args()

    device     = "cuda" if torch.cuda.is_available() else "cpu"
    categories = ["pcb1", "pcb2", "pcb3", "pcb4"]
    engine     = CDADEngine(device)

    opt_diff = torch.optim.AdamW(
        list(engine.unet.parameters()) + list(engine.defect_cond.parameters()),
        lr=1e-5
    )
    opt_amn = torch.optim.AdamW(engine.amn.parameters(), lr=1e-4)
    report  = []

    for task_id, cat in enumerate(categories):
        csv_p = os.path.join(args.data_root, cat, "image_anno.csv")
        if not os.path.exists(csv_p):
            continue

        df      = pd.read_csv(csv_p)
        defects = sorted(set([
            p.strip()
            for l in df[df['label'] != 'normal']['label'].unique()
            for p in str(l).split(',') if p.strip()
        ]))
        cmap    = {n: i for i, n in enumerate(defects)}
        normals = df[df['label'].str.lower() == 'normal']['image'].tolist()

        print(f"\n{'='*60}")
        print(f"[Task {task_id} | {cat}] 학습 시작 | 결함: {defects}")
        print(f"{'='*60}")

        ds = DefectDataset(args.data_root, cat, defects)
        dl = DataLoader(ds, batch_size=1, shuffle=True)

        for e in range(args.epochs):
            pbar = tqdm(dl, desc=f"[{cat}] Epoch {e+1}/{args.epochs}")
            a_losses, d_losses = [], []
            for b in pbar:
                a_loss = engine.train_amn_step(b, opt_amn)
                d_loss = engine.train_diffusion_step(b, opt_diff, task_id)
                a_losses.append(a_loss)
                d_losses.append(d_loss)
                pbar.set_postfix(
                    amn=f"{np.mean(a_losses):.4f}",
                    diff=f"{np.mean(d_losses):.4f}"
                )

        engine.update_gp_basis(dl, task_id)
        print(f"[{cat}] GP 기저 업데이트 완료")

        for subdir in ["images", "masks", "labels"]:
            os.makedirs(os.path.join(args.output_dir, cat, subdir), exist_ok=True)


        for d in defects:
            rows = df[df['label'].str.contains(d, na=False)]
            if rows.empty:
                continue
            for i in tqdm(range(args.num_single), desc=f"[{cat}] single/{d}"):
                row   = rows.sample(1).iloc[0]
                n_img = Image.open(os.path.join(args.data_root, random.choice(normals))).convert("RGB")
                d_img = Image.open(os.path.join(args.data_root, row['image'])).convert("RGB")
                m_img = load_mask(os.path.join(args.data_root, row['mask']))

                gen, f_mask, clip_s = engine.generate_single(
                    n_img, d_img, m_img, d, cat
                )
                inte, psnr = calculate_metrics(n_img, gen, f_mask)

                name = f"single_{d}_{i}"
                gen.save(os.path.join(args.output_dir, cat, "images", f"{name}.png"))
                f_mask.save(os.path.join(args.output_dir, cat, "masks", f"{name}.png"))
                bbox = get_bbox_from_mask(f_mask, cmap[d])
                if bbox:
                    with open(os.path.join(
                        args.output_dir, cat, "labels", f"{name}.txt"
                    ), "w") as f:
                        f.write(
                            f"{bbox[0]} {bbox[1]:.6f} {bbox[2]:.6f} "
                            f"{bbox[3]:.6f} {bbox[4]:.6f}"
                        )
                report.append({
                    'filename': name, 'cat': cat, 'type': 'single',
                    'defect': d, 'clip': clip_s, 'intensity': inte, 'psnr': psnr
                })


        for i in tqdm(range(args.num_compound), desc=f"[{cat}] compound"):
            if len(defects) < 2:
                break
            d1, d2 = random.sample(defects, 2)
            r1     = df[df['label'].str.contains(d1, na=False)].sample(1).iloc[0]
            r2     = df[df['label'].str.contains(d2, na=False)].sample(1).iloc[0]

            n_img  = Image.open(os.path.join(args.data_root, random.choice(normals))).convert("RGB")
            d1_img = Image.open(os.path.join(args.data_root, r1['image'])).convert("RGB")
            d2_img = Image.open(os.path.join(args.data_root, r2['image'])).convert("RGB")
            m1_img = load_mask(os.path.join(args.data_root, r1['mask']))
            m2_img = load_mask(os.path.join(args.data_root, r2['mask']))

            gen, comb_mask, ref_masks, clip_s = engine.generate_compound(
                n_img, [d1_img, d2_img], [m1_img, m2_img],
                [d1, d2], cat
            )
            inte, psnr = calculate_metrics(n_img, gen, comb_mask)

            name = f"compound_{d1}_{d2}_{i}"
            gen.save(os.path.join(args.output_dir, cat, "images", f"{name}.png"))
            comb_mask.save(os.path.join(args.output_dir, cat, "masks", f"{name}.png"))
            with open(os.path.join(
                args.output_dir, cat, "labels", f"{name}.txt"
            ), "w") as f:
                for dn, m_ref in zip([d1, d2], ref_masks):
                    b = get_bbox_from_mask(m_ref.resize((512, 512)), cmap[dn])
                    if b:
                        f.write(
                            f"{b[0]} {b[1]:.6f} {b[2]:.6f} "
                            f"{b[3]:.6f} {b[4]:.6f}\n"
                        )
            report.append({
                'filename': name, 'cat': cat, 'type': 'compound',
                'defect': f"{d1}+{d2}", 'clip': clip_s,
                'intensity': inte, 'psnr': psnr
            })

    pd.DataFrame(report).to_csv(
        os.path.join(args.output_dir, "report.csv"), index=False
    )
    print(f"\n완료! 저장 위치: {args.output_dir}")